export const materialData = [
  { id: 1, name: 'Vải lanh', value: 'linen' },
  { id: 2, name: 'Vải bố', value: 'burlap' },
  { id: 3, name: 'Lụa', value: 'silk' },
  { id: 4, name: 'Vải cotton', value: 'cotton' },
  { id: 5, name: 'Vải jeans', value: 'jeans' },
  { id: 6, name: 'Nhung', value: 'velvet' },
  { id: 7, name: 'Len', value: 'wool' },
  { id: 8, name: 'Da lộn', value: 'suede' },
  { id: 9, name: 'Vải tweed', value: 'tweed' },
  { id: 10, name: 'Vải sequin', value: 'sequin' },
  { id: 11, name: 'Da', value: 'leather' },
  { id: 12, name: 'Vải chiffon', value: 'chiffon' },
  { id: 13, name: 'Vải dệt kim', value: 'knit' },
  { id: 14, name: 'Vải lưới', value: 'mesh' },
  { id: 15, name: 'Vải ren', value: 'lace' },
  { id: 16, name: 'Vải xốp', value: 'foam fabric' },
  { id: 17, name: 'Vải tuyết', value: 'snow fabric' },
  { id: 18, name: 'Vải kaki', value: 'khaki' },
  { id: 19, name: 'Vải organza', value: 'organza' },
  { id: 20, name: 'Vải tổng hợp', value: 'synthetic fabric' },
  { id: 21, name: 'Vải satin', value: 'satin' },
  { id: 22, name: 'Vải taffeta', value: 'taffeta' },
  { id: 23, name: 'Vải brocade', value: 'brocade' },
  { id: 24, name: 'Vải dệt', value: 'woven' },
  { id: 25, name: 'Vải dệt mát', value: 'cool knit' },
  { id: 26, name: 'Vải kate', value: 'kate' },
  { id: 27, name: 'Vải umi', value: 'umi' },
  { id: 28, name: 'Vải dệt kim', value: 'knit fabric' },
  { id: 29, name: 'Vải lanh', value: 'linen cloth' },
  { id: 30, name: 'Vải voile', value: 'sand voile' },
]
