export const sizes = [
  { id: 'S', name: 's', value: 'S' },
  { id: 'M', name: 'm', value: 'M' },
  { id: 'L', name: 'l', value: 'L' },
  { id: 'XL', name: 'xl', value: 'XL' },
  { id: 'XXL', name: 'xxl', value: 'XXL' },
  { id: 'XXXL', name: 'xxxl', value: 'XXXL' },
  { id: 'XS', name: 'xs', value: 'XS' },
  { id: 'FREESZIE', name: 'freeszie', value: 'FREESZIE' },
  { id: 'NUM_36', name: '36', value: '36' },
  { id: 'NUM_37', name: '37', value: '37' },
  { id: 'NUM_38', name: '38', value: '38' },
  { id: 'NUM_39', name: '39', value: '39' },
  { id: 'NUM_40', name: '40', value: '40' },
  { id: 'NUM_41', name: '41', value: '41' },
  { id: 'NUM_42', name: '42', value: '42' },
  { id: 'NUM_43', name: '43', value: '43' },
  { id: 'NUM_44', name: '44', value: '44' },
  { id: 'NUM_45', name: '45', value: '45' },
  { id: 'NUM_46', name: '46', value: '46' },
]

export const hobbies = [
  { id: 'SPORT', name: 'thể thao', value: 'sport' },
  { id: 'TRAVEL', name: 'du lịch', value: 'travel' },
  { id: 'MUSIC', name: 'âm nhạc', value: 'music' },
  { id: 'READING', name: 'đọc sách', value: 'reading' },
  { id: 'MOVIE', name: 'xem phim', value: 'movie' },
  { id: 'GAME', name: 'trò chơi', value: 'game' },
  { id: 'SHOPPING', name: 'mua sắm', value: 'shopping' },
  { id: 'COOKING', name: 'nấu ăn', value: 'cooking' },
  { id: 'PHOTOGRAPHY', name: 'nhiếp ảnh', value: 'photography' },
  { id: 'DANCE', name: 'nhảy múa', value: 'dance' },
  { id: 'FISHING', name: 'câu cá', value: 'fishing' },
  { id: 'CAMPING', name: 'cắm trại', value: 'camping' },
  { id: 'HIKING', name: 'đi bộ đường dài', value: 'hiking' },
  { id: 'CYCLING', name: 'đạp xe', value: 'cycling' },
  { id: 'SWIMMING', name: 'bơi lội', value: 'swimming' },
  { id: 'YOGA', name: 'yoga', value: 'yoga' },
  { id: 'MEDITATION', name: 'thiền', value: 'meditation' },
  { id: 'RUNNING', name: 'chạy bộ', value: 'running' },
  { id: 'SKATING', name: 'trượt băng', value: 'skating' },
  { id: 'SKATEBOARD', name: 'trượt ván', value: 'skateboard' },
  { id: 'SURFING', name: 'lướt sóng', value: 'surfing' },
  { id: 'SKIING', name: 'trượt tuyết', value: 'skiing' },
  { id: 'SNOWBOARD', name: 'trượt ván tuyết', value: 'snowboard' },
  { id: 'CLIMBING', name: 'leo núi', value: 'climbing' },
  { id: 'OTHER', name: 'khác', value: 'other' },
]
